# Generated by Django 5.0.6 on 2024-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemQty', models.IntegerField()),
                ('isChecked', models.BooleanField(default=False)),
            ],
        ),
    ]
